## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##
##                                                                                     ##
## ████████╗ ██████╗       █████╗ ███╗   ██╗████████╗██╗██████╗  ██████╗ ████████╗     ##
## ╚══██╔══╝██╔════╝      ██╔══██╗████╗  ██║╚══██╔══╝██║██╔══██╗██╔═══██╗╚══██╔══╝     ##
##    ██║   ██║ ████║     ███████║██╔██╗ ██║   ██║   ██║██████╔╝██║   ██║   ██║        ##
##    ██║   ██║   ██║     ██╔══██║██║╚██╗██║   ██║   ██║██╔══██╗██║   ██║   ██║        ##
##    ██║   ╚██████╔╝     ██║  ██║██║ ╚████║   ██║   ██║██████╔╝╚██████╔╝   ██║        ##
##    ╚═╝    ╚═════╝      ╚═╝  ╚═╝╚═╝  ╚═══╝   ╚═╝   ╚═╝╚═════╝  ╚═════╝    ╚═╝        ##
##                                                                                     ##
## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##

# TG-AntiBot Advanced Configuration
# Developed by Techinpoint Gamerz
# Version: 2.0.0

# ================================
# GENERAL SETTINGS
# ================================
enabled: true
debug: false

# ================================
# BOT PROTECTION SYSTEM
# ================================
protection:
  # Thresholds for attack detection
  join-threshold: 10              # Joins per second to trigger lockdown mode
  ping-threshold: 50              # Pings per second to trigger strict mode
  packet-threshold: 100           # Packets per second threshold
  
  # Protection behavior
  kick-on-lockdown: true          # Kick suspicious players during lockdown
  cooldown-time: 60000            # Time in ms before returning to normal mode
  temp-blacklist-duration: 300    # Temporary blacklist duration in seconds
  
  # Trusted player settings
  trusted-player-time: 3600000    # Playtime in ms to be considered trusted (1 hour)
  trusted-connection-count: 5     # Connection count to be considered trusted

# ================================
# SECURITY CHECKS
# ================================
checks:
  # Connection speed analysis
  connection-speed:
    enabled: true
    max-per-minute: 5             # Maximum connections per minute per IP
    min-interval: 1000            # Minimum time between connections (ms)
  
  # Nickname validation
  nickname:
    enabled: true
    block-non-ascii: false        # Block non-ASCII characters in nicknames
    blacklist:                    # Blacklisted nickname patterns
      - "bot"
      - "hack"
      - "spam"
      - "test"
      - "player"
  
  # Account limit per IP
  account-limit:
    enabled: true
    max-accounts: 3               # Maximum accounts per IP address
  
  # Reconnection analysis
  reconnect:
    enabled: true
    min-time: 2000                # Minimum time between reconnections (ms)
  
  # Geographic location filtering
  geolocation:
    enabled: false                # Enable country-based blocking
    blocked-countries: []         # List of blocked country codes (e.g., ["CN", "RU"])
  
  # Behavioral analysis
  behavior-analysis:
    enabled: true
    suspicion-threshold: 50       # Suspicion score threshold for blocking

# ================================
# ATTACK ANALYSIS
# ================================
analysis:
  coordinated-attack-threshold: 20  # Attacks per minute to detect coordination
  repeat-offender-threshold: 5      # Attacks from same IP to blacklist

# ================================
# SECURITY RISK ASSESSMENT
# ================================
security:
  high-risk-threshold: 70         # Risk score for high-risk classification
  medium-risk-threshold: 40       # Risk score for medium-risk classification
  whitelist: []                   # Whitelisted IP addresses
  blacklist: []                   # Blacklisted IP addresses

# ================================
# VPN/PROXY PROTECTION
# ================================
antivpn:
  enabled: true
  strict-mode: true               # Block all detected VPN/Proxy connections
  cache-duration-minutes: 1440    # Cache VPN check results (24 hours)
  
  providers:
    proxycheck:
      api-key: "YOUR_API_KEY_HERE"  # Get from https://proxycheck.io/
      timeout: 5000               # API timeout in milliseconds
    
    # Alternative providers (choose one)
    # iphub:
    #   api-key: "YOUR_IPHUB_KEY"
    # vpnapi:
    #   api-key: "YOUR_VPNAPI_KEY"

# ================================
# FIREWALL SYSTEM
# ================================
firewall:
  enabled: true
  auto-ban-duration: 3600         # Auto-ban duration in seconds (1 hour)
  
  # IP Management
  blocked-ips: []                 # Manually blocked IP addresses
  whitelist-ips:                  # Always allowed IP addresses
    - "127.0.0.1"
    - "::1"
  
  # Advanced filtering
  block-tor-exits: false          # Block known Tor exit nodes
  block-hosting-providers: false  # Block known hosting/VPS providers

# ================================
# JOIN RATE LIMITING
# ================================
join-limit:
  max-joins: 5                    # Maximum players allowed to join per interval
  interval-seconds: 1             # Time window for join limit
  burst-protection: true          # Enable burst join protection

# ================================
# PLAYER COOLDOWNS
# ================================
cooldowns:
  join-delay-ms: 3000             # Per-player join cooldown
  command-delay-seconds: 3        # Command usage cooldown
  bypass-permission: "tga.bypass" # Permission to bypass all cooldowns

# ================================
# NOTIFICATIONS & ALERTS
# ================================
alerts:
  staff-permission: "tga.alerts"  # Permission to receive alerts
  broadcast-attacks: true         # Broadcast attack notifications
  log-to-file: true              # Log events to file
  log-file-name: "tga-security.log"
  
  # Notification types
  actionbar-updates: true         # Show real-time stats in action bar
  title-notifications: true      # Show attack alerts as titles
  bossbar-status: true           # Show protection status in boss bar

# ================================
# ADVANCED FEATURES
# ================================
advanced:
  # Machine learning (experimental)
  ml-detection: false             # Enable ML-based bot detection
  learning-mode: false            # Learn from player behavior patterns
  
  # Integration options
  discord-webhook: ""             # Discord webhook for alerts
  database-logging: false         # Log to database instead of files
  
  # Performance optimization
  async-processing: true          # Process checks asynchronously
  cache-size: 10000              # Maximum cached player profiles
  cleanup-interval: 3600         # Profile cleanup interval (seconds)

# ================================
# COMPATIBILITY
# ================================
compatibility:
  # Plugin integrations
  authme-integration: true        # Integrate with AuthMe
  essentials-integration: true    # Integrate with Essentials
  luckperms-integration: true     # Integrate with LuckPerms
  
  # Protocol support
  viaversion-support: true        # Support ViaVersion clients
  protocollib-hooks: true         # Use ProtocolLib if available

# ================================
# MESSAGES CUSTOMIZATION
# ================================
messages:
  # You can override any message from messages.yml here
  # Example:
  # prefix: "&7[&cTG-AntiBot&7] "
  # attack-detected: "&c[ALERT] Attack detected: {type}"